### ISSUE TITLE
add a .travis.yml for travis-ci 

### ISSUE THREAD

**Issue by jrobeson** [sandeepmistry/noble#317]
It'd be nice to have travis run all tests for PRs/pushes.

**Comment by jrobeson** [comment]
I already gave this a try on my github fork, and we already have a build failure on nodejs 0.8.x If this failure isn't transient, then it seems like we should update the minimum node engine version in package.json.

You can see the the build failures here: https://travis-ci.org/jrobeson/noble/builds/105102613

Here's the .travis.yml I'm using (to save a clickover to the repo)

```yml
language: node_js
node_js:
  - "5"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
```
