### ISSUE TITLE
Noble Causing Appveyor to Fail

### ISSUE THREAD

**Issue by aj-ptw** [sandeepmistry/noble#506]
Attempting to build [OpenBCI_Ganglion_Electron](https://github.com/OpenBCI/OpenBCI_Ganglion_Electron) with this library inside an electron app. 

The bug is coming from trying to build for windows using [Appveyor CI](https://ci.appveyor.com/project/aj-ptw/openbci-ganglion-electron)

My `appveyor.yaml` is:
```yaml
os: unstable

environment:
  matrix:
    - nodejs_version: 7

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - ps: git clone -q --branch=ganglion https://github.com/aj-ptw/OpenBCI_NodeJS.git C:\projects\OpenBCI_NodeJS
  - ps: cd app
  - ps: npm install C:\projects\OpenBCI_NodeJS

test_script:
  - node --version
  - npm run release

artifacts:
  - path: dist
    name: GanglionHub
```
The error we are getting [is here](https://ci.appveyor.com/project/aj-ptw/openbci-ganglion-electron/build/15#L553) as it looks like some USB dependency is throwing a fit.
A quick snippet of the error is here:
```bash
npm WARN openbci-ganglion-hub@0.1.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 (node_modules\usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

Would love to get this solved and I believe this could result in a PR to the main repo to add an appveyor example for the next person! 

Thanks. So far this project has been great on macOS, but stubbing toes when trying to build on a windows machine. 

You can see [what software comes default on appveyor here](https://www.appveyor.com/docs/installed-software/) and it already has Python 2.7.

I could see usb being a problem here because well, it's a virtual machine and why would it have drivers for usb?
